#!/bin/bash
clear
ns_domain="cat /etc/xray/dns"
function ns_domain_cloudflare() {
    DOMEN="slowdns.app"
    sub=$(tr </dev/urandom -dc a-z0-9 | head -c2)
    domain="ns-${sub}.slowdns.app"
    echo -e "${domain}" >/etc/xray/dns
    CF_ID="nuryahyamuhaimin@gmail.com"
    CF_KEY="9dd2f30c099dbcf541cbd5c188d61ce060cf7"
    set -euo pipefail
    IP=$(wget -qO- ipinfo.io/ip)
    ZONE=$(curl -sLX GET "https://api.cloudflare.com/client/v4/zones?name=${DOMEN}&status=active" \
        -H "X-Auth-Email: ${CF_ID}" \
        -H "X-Auth-Key: ${CF_KEY}" \
        -H "Content-Type: application/json" | jq -r .result[0].id)

    RECORD=$(curl -sLX GET "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records?name=${domain}" \
        -H "X-Auth-Email: ${CF_ID}" \
        -H "X-Auth-Key: ${CF_KEY}" \
        -H "Content-Type: application/json" | jq -r .result[0].id)

    if [[ "${#RECORD}" -le 10 ]]; then
        RECORD=$(curl -sLX POST "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records" \
            -H "X-Auth-Email: ${CF_ID}" \
            -H "X-Auth-Key: ${CF_KEY}" \
            -H "Content-Type: application/json" \
            --data '{"type":"A","name":"'${domain}'","content":"'${IP}'","proxied":false}' | jq -r .result.id)
    fi

    RESULT=$(curl -sLX PUT "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records/${RECORD}" \
        -H "X-Auth-Email: ${CF_ID}" \
        -H "X-Auth-Key: ${CF_KEY}" \
        -H "Content-Type: application/json" \
        --data '{"type":"A","name":"'${domain}'","content":"'${IP}'","proxied":false}')

}

apt install golang -y >/dev/null 2>&1
ns_domain_cloudflare >/dev/null 2>&1
mkdir -m 777 /etc/slowdns
wget -q -O /root/plugin.zip "https://github.com/rullpqh/Autoscript-vps/raw/main/X-SlowDNS/plugin.zip"
unzip plugin.zip
rm -r -f plugin.zip
cd dnstt-plugin
cd dnstt-client
go build
mv dnstt-client /etc/slowdns/client
cd /root/dnstt-plugin/dnstt-server
go build
./dnstt-server -gen-key -privkey-file server.key -pubkey-file server.pub
mv dnstt-server /etc/slowdns/server
mv server.key /etc/slowdns/
mv server.pub /etc/slowdns/
wget -O /etc/systemd/system/dns-client.service "https://raw.githubusercontent.com/rullpqh/Autoscript-vps/main/X-SlowDNS/client" >/dev/null 2>&1
wget -O /etc/systemd/system/dns-server.service "https://raw.githubusercontent.com/rullpqh/Autoscript-vps/main/X-SlowDNS/server" >/dev/null 2>&1
sed -i "s/xxxx/$domain/g" /etc/systemd/system/dns-client.service >/dev/null 2>&1
sed -i "s/xxxx/$domain/g" /etc/systemd/system/dns-server.service >/dev/null 2>&1
chmod +x /etc/slowdns/*  >/dev/null 2>&1
chmod +x /etc/systemd/system/client.service >/dev/null 2>&1
chmod +x /etc/systemd/system/server.service >/dev/null 2>&1
