#!/bin/bash
clear
GIT_HUB="https://github.com/rullpqh/Autoscript-vps/raw/main/"
function ns_domain_cloudflare() {
     DOMAIN="slowdns.app"
     DAOMIN=$(cat /etc/xray/domain)
     SUB=$(tr </dev/urandom -dc a-z0-9 | head -c2)
     SUB_DOMAIN=${SUB}."slowdns.app"
     NS_DOMAIN=ns.${SUB_DOMAIN}
     CF_ID="nuryahyamuhaimin@gmail.com"
     CF_KEY="9dd2f30c099dbcf541cbd5c188d61ce060cf7"
     set -euo pipefail
     IP=$(wget -qO- ipinfo.io/ip)
     echo "Updating DNS NS for ${NS_DOMAIN}..."
     ZONE=$(curl -sLX GET "https://api.cloudflare.com/client/v4/zones?name=${DOMAIN}&status=active" \
          -H "X-Auth-Email: ${CF_ID}" \
          -H "X-Auth-Key: ${CF_KEY}" \
          -H "Content-Type: application/json" | jq -r .result[0].id)

     RECORD=$(curl -sLX GET "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records?name=${NS_DOMAIN}" \
          -H "X-Auth-Email: ${CF_ID}" \
          -H "X-Auth-Key: ${CF_KEY}" \
          -H "Content-Type: application/json" | jq -r .result[0].id)

     if [[ "${#RECORD}" -le 10 ]]; then
          RECORD=$(curl -sLX POST "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records" \
               -H "X-Auth-Email: ${CF_ID}" \
               -H "X-Auth-Key: ${CF_KEY}" \
               -H "Content-Type: application/json" \
               --data '{"type":"NS","name":"'${NS_DOMAIN}'","content":"'${DAOMIN}'","ttl":120,"proxied":false}' | jq -r .result.id)
     fi

     RESULT=$(curl -sLX PUT "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records/${RECORD}" \
          -H "X-Auth-Email: ${CF_ID}" \
          -H "X-Auth-Key: ${CF_KEY}" \
          -H "Content-Type: application/json" \
          --data '{"type":"NS","name":"'${NS_DOMAIN}'","content":"'${DAOMIN}'","ttl":120,"proxied":false}')
     echo "Host : $NS_DOMAIN"
     echo $NS_DOMAIN >/etc/xray/dns
}

apt install golang -y >/dev/null 2>&1
ns_domain_cloudflare >/dev/null 2>&1
mkdir -m 777 /etc/slowdns
wget -q -O /root/plugin.zip "${GIT_HUB}X-SlowDNS/plugin.zip"
unzip plugin.zip
rm -r -f plugin.zip
cd dnstt-plugin
cd dnstt-client
go build
mv dnstt-client /etc/slowdns/client
cd /root/dnstt-plugin/dnstt-server
go build
./dnstt-server -gen-key -privkey-file server.key -pubkey-file server.pub
mv dnstt-server /etc/slowdns/server
mv server.key /etc/slowdns/
mv server.pub /etc/slowdns/
wget -O /etc/systemd/system/client.service "${GIT_HUB}X-SlowDNS/client" >/dev/null 2>&1
wget -O /etc/systemd/system/server.service "${GIT_HUB}X-SlowDNS/server" >/dev/null 2>&1
sed -i "s/xxxx/$NS_DOMAIN/g" /etc/systemd/system/client.service >/dev/null 2>&1
sed -i "s/xxxx/$NS_DOMAIN/g" /etc/systemd/system/server.service >/dev/null 2>&1
chmod +x /etc/slowdns/server.key
chmod +x /etc/slowdns/server.pub
chmod +x /etc/slowdns/server
chmod +x /etc/slowdns/client
